apiVersion: v1
kind: Secret
metadata:
  name: safechat-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres.kdzzpckmzhgaqqielhii:Z0BBhub3yKXx7siY@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
  OPENROUTER_API_KEY: "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"